Experimental: Don't use SpooledTemporaryFile
The following 500 error was occurring on image upload:
File /usr/srv/app/./helpers/storage.py line 80 in _save args locals
  return super(MediaRootS3BotoStorage, self)._save(name, content_autoclose)
File /usr/lib/python3.8/site-packages/storages/backends/s3boto3.py line 466 in _save args locals
  if content.seekable():
AttributeError: 'SpooledTemporaryFile' object has no attribute 'seekable'

STF does not expose the seekable attribute, a known deficiency.
https://bugs.python.org/issue26175

I was unable to reproduce this error locally, probably because I'm not saving to S3.