Suppress errors about static files not being in the manifest
In CI we'd get a wall of the following error:

```
File "/usr/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
  raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'wagtailnhsukfrontend/css/wagtail-nhsuk-frontend.min.css'
```

We don't currently have a staticfiles.json; this is related to the version bump, I think

Docs: http://whitenoise.evans.io/en/stable/django.html?highlight=manifest_strict#WHITENOISE_MANIFEST_STRICT