Remove closure-compiler
Docker build and CI were broken with the error message:

Step 5/31 : RUN apk add closure-compiler --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted &&     rm -f /tmp/* /etc/apk/cache/* /root/.cache
 ---> Running in 550968f4fc23
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  closure-compiler (no such package):
    required by: world[closure-compiler]

I'm not entirely sure what the effects of removing this package and no longer cleaning the javascript with
it are: I suspect it is not critical -- increased javascript size, potentially missing a few optimisations.

There are links in Google search to https://pkgs.alpinelinux.org/package/edge/testing/x86/closure-compiler
with text suggesting a v20171203-r1 version existed, but the page itself 404s. A link does exist in the
AUR (https://aur.archlinux.org/packages/closure-compiler)

Some notes on next steps to try to reintegrate closure-compiler at https://github.com/nhsx/nhsx-website/pull/702#issuecomment-1139793130