Remove closure-compiler
Docker build and CI were broken with the error message:

Step 5/31 : RUN apk add closure-compiler --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted &&     rm -f /tmp/* /etc/apk/cache/* /root/.cache
 ---> Running in 550968f4fc23
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  closure-compiler (no such package):
    required by: world[closure-compiler]

The closure-compiler does not appear to obviously be used anywhere, so we have removed this dependency.

There are links in Google search to https://pkgs.alpinelinux.org/package/edge/testing/x86/closure-compiler
with text suggesting a v20171203-r1 version existed, but the page itself 404s. A link does exist in the
AUR (https://aur.archlinux.org/packages/closure-compiler)