Remove jsmin due to install errors.
jsmin appears to be a dev dependency that is never used: 'ack jsmin' returns no results outside of the poetry files.

Error when running poetry:

  EnvCommandError

  Command ['/usr/bin/python3', '-m', 'pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/14/a6/f1/6eb7dfe010a4d3088540bd5bad8e4f2f8709274100378b1c312abc81be/jsmin-2.2.2.tar.gz'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/14/a6/f1/6eb7dfe010a4d3088540bd5bad8e4f2f8709274100378b1c312abc81be/jsmin-2.2.2.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5zzppqgd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5zzppqgd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tt32fn8l
           cwd: /tmp/pip-req-build-5zzppqgd/
      Complete output (1 lines):
      error in jsmin setup command: use_2to3 is invalid.
      ----------------------------------------
  WARNING: Discarding file:///root/.cache/pypoetry/artifacts/14/a6/f1/6eb7dfe010a4d3088540bd5bad8e4f2f8709274100378b1c312abc81be/jsmin-2.2.2.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

  at ~/.poetry/lib/poetry/utils/env.py:1101 in _run
      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│
      1103│         return decode(output)
      1104│
      1105│     def execute(self, bin, *args, **kwargs):

Also incidently updates some other libraries:
  • Updating sqlparse (0.4.1 -> 0.4.2)
  • Updating openpyxl (3.0.7 -> 3.0.8)
  • Updating botocore (1.21.36 -> 1.21.41)
  • Updating decorator (5.0.9 -> 5.1.0)
  • Updating matplotlib-inline (0.1.2 -> 0.1.3)
  • Updating django-otp (1.0.6 -> 1.1.0)
  • Updating boto3 (1.18.36 -> 1.18.41)