Require non-broken ast >= 1.5.0
Black fails in CI:

```
Creating nhsx-website_test_run ... done
Traceback (most recent call last):
...
  File "/usr/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/usr/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: Error relocating /usr/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-musl.so: _PyUnicode_DecodeUnicodeEscape: symbol not found
```

https://stackoverflow.com/questions/69912264/python-3-9-8-fails-using-black-and-importing-typed-ast-ast3
https://github.com/python/typed_ast/issues/169#issuecomment-966711709