Revert poetry.lock and pyproject.toml to version on master
We encountered a problem where a Promo Group containing at least 1
item would cause a 500 error:

```
File /usr/lib/python3.9/site-packages/wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py:82 in chunk
return [input_list[i:i + size] for i in range(0, len(input_list), size)]
File /usr/lib/python3.9/site-packages/wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py:82 in <listcomp>
return [input_list[i:i + size] for i in range(0, len(input_list), size)]
File /usr/lib/python3.9/site-packages/wagtail/core/blocks/list_block.py:85 in __getitem__ args locals
return self.bound_blocks[i].value
AttributeError: 'list' object has no attribute 'value'
```

We reverted most of the changes back (except for the removed migration
core/0047 and the actual migration core/0048, and an update to how
poetry itself is installed) and got it working, but that didn't apply all
the changes we'd wanted to make.

If this works, we'll have a sensible setup from which to try to understand
the underlying reasons for this error. (It works nicely locally.)